export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh

zplug "b-ryan/powerline-shell"

# syntax
zplug "chrissicool/zsh-256color"
zplug "Tarrasch/zsh-colors"
zplug "zsh-users/zsh-syntax-highlighting", defer:2
zplug "ascii-soup/zsh-url-highlighter"

# tools
zplug "zsh-users/zsh-autosuggestions"

# 大文字小文字を区別しない
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

# lsコマンドで色分けする
zstyle ':completion:*' list-colors $LSCOLORS
alias ls='ls -G'

zplug load
export PATH=$HOME/.nodebrew/current/bin:$PATH
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# ==========
# prompt
# ==========
autoload -U promptinit; promptinit
# optionally define some options
PURE_CMD_MAX_EXEC_TIME=10

# change the path color
zstyle :prompt:pure:path color magenta

# change the color for both `prompt:success` and `prompt:error`
zstyle ':prompt:pure:prompt:*' color cyan

# turn on git stash status
zstyle :prompt:pure:git:stash show yes

prompt pure

# ===========
# pyenv
# ==========
# ~/.pyenvを/usr/loca/var/pyenvに変更
export PYENV_ROOT=/usr/local/var/pyenv

# 自動補完機能
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

# ==========
# alias
# ==========

alias vim="nvim"

